services:
  - type: web
    name: guilttrip-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
